CP_ONLINE_TEST_PRIVACY = ""
CP_ONLINE_TEST_PUBLIC = ""

CP_ONLINE_DEV_PRIVACY = ""
CP_ONLINE_DEV_PUBLIC = ""

CP_ONLINE_PREP_PRIVACY = ""
CP_ONLINE_PREP_PUBLIC = ""

CP_ONLINE_PROD_PRIVACY = ""
CP_ONLINE_PROD_PUBLIC = ""

CP_ONLINE_PROD_IP_PRIVACY = ""
CP_ONLINE_PROD_IP_PUBLIC = ""
